#!/usr/bin/env python3
"""tokens.json -> 全仓库同步器。

职责
  1. 把 tokens.json 生成的 CSS 变量块内联注入每个 HTML 的 tokens:start/tokens:end 标记区（首次运行时替换原有 :root 块）。
     之所以内联而不是外链 CSS：交付物必须双击就能打开、卡片要走 html2canvas 导出、公众号模板必须全内联。
  2. 用 color_migration 表清理 tokens 区块之外的裸色值（含 rgba 三元组），消除旧配色残留。
  3. 把品牌色用法矩阵自动写进 brand-dna.md 的 tokens:matrix 标记区，保证文档不与 tokens.json 漂移。

用法
  python scripts/build_tokens.py           # 写入
  python scripts/build_tokens.py --check   # 只校验，有差异则退出码 1（CI 用）
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TOKENS = ROOT / "tokens.json"

CSS_START = "/* tokens:start — generated by scripts/build_tokens.py, do not edit */"
CSS_END = "/* tokens:end */"
MD_START = "<!-- tokens:matrix:start — generated by scripts/build_tokens.py, do not edit -->"
MD_END = "<!-- tokens:matrix:end -->"
# 文档里故意写出的「已弃用色值」不能被迁移表改掉，否则说明文字自相矛盾。
NOMIGRATE_START = "<!-- ds-nomigrate:start -->"
NOMIGRATE_END = "<!-- ds-nomigrate:end -->"

# 注入 CSS 变量块的文件（有 :root 的）
CSS_TARGETS = [
    "assets/template-tutorial.html",
    "assets/template-landing.html",
    "assets/template-app.html",
    "assets/template-cards.html",
    "demo-tutorial.html",
    "demo-landing.html",
    "demo-app.html",
    "demo-cards.html",
    "demo-layouts.html",
    "demo-readme-tutorial.html",
    "components-preview.html",
    "index.html",
]
# 只做色值迁移、不注入变量块的文件（全内联样式 / 纯文档）
MIGRATE_ONLY = [
    "assets/template-wechat.html",
    "assets/demo-wechat.html",
    "references/components.md",  # 拆分后是指针；分片由 migrate_targets() 动态展开
    "references/layouts.md",
    "references/scene-tutorial.md",
    "references/scene-landing.md",
    "references/scene-app.md",
    "references/scene-cards.md",
    "references/scene-wechat.md",
    "references/checklist.md",
]


def migrate_targets() -> list[str]:
    """MIGRATE_ONLY 加上 references/components/ 下的全部分片。

    组件库拆分后分片是动态的（以后调分类会增删文件），写死列表必然漏掉，
    漏掉的分片就会留着旧色值不迁移。
    """
    rels = list(MIGRATE_ONLY)
    comp = ROOT / "references" / "components"
    if comp.is_dir():
        rels += [p.relative_to(ROOT).as_posix() for p in sorted(comp.glob("*.md"))]
    return rels


# ---------- 对比度 ----------
def hex2rgb(h: str) -> tuple[int, int, int]:
    h = h.lstrip("#")
    if len(h) == 3:
        h = "".join(c * 2 for c in h)
    return tuple(int(h[i : i + 2], 16) for i in (0, 2, 4))  # type: ignore[return-value]


def relative_luminance(hex_color: str) -> float:
    chan = [c / 255 for c in hex2rgb(hex_color)]
    chan = [c / 12.92 if c <= 0.03928 else ((c + 0.055) / 1.055) ** 2.4 for c in chan]
    return 0.2126 * chan[0] + 0.7152 * chan[1] + 0.0722 * chan[2]


def parse_rgba(value: str) -> tuple[tuple[int, int, int], float]:
    """把 rgba(r, g, b, a) / rgb(r, g, b) 解析成 ((r,g,b), alpha)。"""
    nums = re.findall(r"[\d.]+%?", value)
    if len(nums) < 3:
        raise ValueError(f"无法解析颜色: {value}")

    def chan(tok: str) -> int:
        if tok.endswith("%"):
            return round(float(tok[:-1]) * 255 / 100)
        return int(float(tok))

    rgb = (chan(nums[0]), chan(nums[1]), chan(nums[2]))
    if len(nums) >= 4:
        a = nums[3]
        alpha = float(a[:-1]) / 100 if a.endswith("%") else float(a)
    else:
        alpha = 1.0
    return rgb, alpha


def composite(top: str, under: str) -> str:
    """把半透明 top 合成到不透明 under 上，返回等效 hex。"""
    (tr, tg, tb), alpha = parse_rgba(top)
    ur, ug, ub = hex2rgb(under)
    out = tuple(round(c * alpha + u * (1 - alpha)) for c, u in ((tr, ur), (tg, ug), (tb, ub)))
    return "#%02X%02X%02X" % out


def max_alpha_for(top_hex: str, ink_hex: str, under_hex: str, target: float) -> float:
    """求同色系色块的最大不透明度上限：超过这个值，配套的 ink 就压不住 target 对比度。"""
    tr, tg, tb = hex2rgb(top_hex)
    best = 0.0
    a = 0.0
    while a <= 1.0001:
        blended = "#%02X%02X%02X" % tuple(
            round(c * a + u * (1 - a)) for c, u in zip((tr, tg, tb), hex2rgb(under_hex))
        )
        if contrast(ink_hex, blended) >= target:
            best = a
        else:
            break
        a += 0.01
    return best


def contrast(a: str, b: str) -> float:
    la, lb = relative_luminance(a), relative_luminance(b)
    hi, lo = max(la, lb), min(la, lb)
    return (hi + 0.05) / (lo + 0.05)


def load_tokens() -> dict:
    return json.loads(TOKENS.read_text(encoding="utf-8"))


# ---------- CSS 生成 ----------
def render_css_block(t: dict) -> str:
    lines = [CSS_START, "    :root {"]
    lines.append(f"      /* ==== v{t['meta']['version']} 品牌色（语义命名） ==== */")
    for key, spec in t["color"].items():
        lines.append(f"      --{key}: {spec['value']};  /* {spec['name']} · {spec['role']} */")
    lines.append("      /* ==== 半透明 ==== */")
    for key, val in t["alpha"].items():
        lines.append(f"      --{key}: {val};")
    if "code_color" in t:
        lines.append("      /* ==== 代码/终端面板 · 具名例外（其他场景禁用冷调） ==== */")
        for key, spec in t["code_color"]["dark"].items():
            lines.append(f"      --{key}: {spec['value']};  /* {spec['role']} */")
        for key, spec in t["code_color"]["light"].items():
            if key.startswith("_"):
                continue
            lines.append(f"      --{key}: {spec['value']};  /* 浅底代码面板 · {spec['role']} */")
    lines.append("      /* ==== 字体栈 ==== */")
    for key, val in t["font"].items():
        lines.append(f"      --font-{key}: {val};")
    lines.append("      /* ==== fluid 字号 ==== */")
    for key, val in t["size"].items():
        lines.append(f"      --fs-{key}: {val};")
    lines.append("      /* ==== 间距 ==== */")
    for key, val in t["space"].items():
        lines.append(f"      --sp-{key}: {val};")
    lines.append("      /* ==== 旧变量名兼容层（新代码请勿使用） ==== */")
    for old, new in t["legacy_aliases"].items():
        lines.append(f"      --{old}: var(--{new});")
    lines.append("    }")
    lines.append(CSS_END)
    return "\n".join(lines)


ROOT_RE = re.compile(r"(?:/\* tokens:start[^\n]*\*/\s*)?:root\s*\{.*?\}(?:\s*/\* tokens:end \*/)?", re.S)


def inject_css(text: str, block: str) -> tuple[str, bool]:
    """替换首个 tokens 区块或 :root 块；没有 :root 的文件在 <style> 开头插入。"""
    if CSS_START in text and CSS_END in text:
        pre, rest = text.split(CSS_START, 1)
        _, post = rest.split(CSS_END, 1)
        new = pre + block + post
        return new, new != text
    m = ROOT_RE.search(text)
    if m:
        new = text[: m.start()] + block + text[m.end() :]
        return new, new != text
    m2 = re.search(r"<style[^>]*>", text)
    if m2:
        new = text[: m2.end()] + "\n" + block + "\n" + text[m2.end() :]
        return new, new != text
    return text, False


# ---------- 色值迁移 ----------
def build_migrators(t: dict):
    hex_map = {k.lower(): v for k, v in t["color_migration"]["hex"].items()}
    hex_re = re.compile("|".join(re.escape(k) for k in sorted(hex_map, key=len, reverse=True)), re.I)

    rgba_map = {tuple(int(x) for x in k.split(",")): v for k, v in t["color_migration"]["rgba"].items()}
    rgba_re = re.compile(r"(rgba?\(\s*)(\d{1,3})(\s*,\s*)(\d{1,3})(\s*,\s*)(\d{1,3})")

    def sub_hex(s: str) -> str:
        return hex_re.sub(lambda m: hex_map[m.group(0).lower()], s)

    def sub_rgba(s: str) -> str:
        def rep(m: re.Match) -> str:
            triple = (int(m.group(2)), int(m.group(4)), int(m.group(6)))
            if triple in rgba_map:
                r, g, b = rgba_map[triple].split(",")
                return f"{m.group(1)}{r}{m.group(3)}{g}{m.group(5)}{b}"
            return m.group(0)

        return rgba_re.sub(rep, s)

    return sub_hex, sub_rgba


def _migrate_protected(text: str, sub_hex, sub_rgba) -> str:
    """跳过 ds-nomigrate 保护区：文档里「为了说明某个色被弃用」而故意写出的旧色值，
    如果也被替换掉，注释就会变成自相矛盾的废话（例:「原 #6F6F81 对比度仅 3.31 已弃用」）。"""
    out: list[str] = []
    idx = 0
    while True:
        s = text.find(NOMIGRATE_START, idx)
        if s == -1:
            out.append(sub_rgba(sub_hex(text[idx:])))
            break
        e = text.find(NOMIGRATE_END, s)
        if e == -1:
            out.append(sub_rgba(sub_hex(text[idx:])))
            break
        e += len(NOMIGRATE_END)
        out.append(sub_rgba(sub_hex(text[idx:s])))
        out.append(text[s:e])
        idx = e
    return "".join(out)


def migrate_outside_tokens(text: str, sub_hex, sub_rgba) -> tuple[str, bool]:
    """只改 tokens 区块之外的色值，区块内由生成器负责。"""
    if CSS_START in text and CSS_END in text:
        pre, rest = text.split(CSS_START, 1)
        block, post = rest.split(CSS_END, 1)
        new = (
            _migrate_protected(pre, sub_hex, sub_rgba)
            + CSS_START
            + block
            + CSS_END
            + _migrate_protected(post, sub_hex, sub_rgba)
        )
    else:
        new = _migrate_protected(text, sub_hex, sub_rgba)
    return new, new != text


# ---------- brand-dna 用法矩阵 ----------
def render_matrix(t: dict) -> str:
    bgs = t["meta"]["contrast_backgrounds"]
    body, large = t["meta"]["contrast_target_body"], t["meta"]["contrast_target_large"]
    out = [
        MD_START,
        "",
        f"<!-- 由 tokens.json v{t['meta']['version']} 自动生成，勿手改 -->",
        "",
        f"| Token | 色值 | 角色 | 对比度 {bgs[0]} / {bgs[1]} | 允许用法 |",
        "|---|---|---|---|---|",
    ]
    for key, spec in t["color"].items():
        v = spec["value"]
        c1, c2 = contrast(v, bgs[0]), contrast(v, bgs[1])
        worst = min(c1, c2)
        if spec.get("text_on_light"):
            tag = "正文可用" if worst >= body else ("仅大字" if worst >= large else "不可作文字")
        else:
            tag = "仅装饰/底色"
        out.append(f"| `--{key}` | `{v}` | {spec['name']} · {spec['role']} | {c1:.2f} / {c2:.2f} · {tag} | {spec['usage']} |")
    out += [
        "",
        f"**判定标准**：正文（<24px 常规字重）需 ≥{body}:1，大字（≥24px 或 ≥19px 粗体）需 ≥{large}:1（WCAG 2.1 AA）。",
        "",
        "**三条必须记住的替换规则**：",
        "",
        f"1. 浅底上写紫色字 → 用 `--accent-ink`，不用 `--accent`（`--accent` 在暖底只有 {contrast(t['color']['accent']['value'], bgs[0]):.2f}:1）。",
        f"2. 深色面板上写紫色字 → 反过来用 `--accent`（在 `--dark-panel` 上 {contrast(t['color']['accent']['value'], t['color']['dark-panel']['value']):.2f}:1），`--accent-ink` 在深底只有 {contrast(t['color']['accent-ink']['value'], t['color']['dark-panel']['value']):.2f}:1。",
        f"3. 红色小字或红底白字按钮 → 用 `--pop-ink`（白字 {contrast('#ffffff', t['color']['pop-ink']['value']):.2f}:1），`--pop` 只能做装饰和 ≥24px 大字（白字仅 {contrast('#ffffff', t['color']['pop']['value']):.2f}:1）。",
        "",
        "**浅色块上的文字**：`--accent-soft` / `--brand-soft` / `--paper` 之上只用 `--ink`、`--ink-light`、`--brand-deep`；不要用 `--ink-faint` 或 `--accent`。",
        "",
        render_wash_table(t),
        "",
        render_code_table(t),
        "",
        "**逃生舱 `--ds-contrast-ok`**：极少数情况下文字并不压在自身背景上（例如白字压在同级蒙版 `.ov` 上）。"
        "此时在该规则里加一条自定义属性说明原因，检查器会跳过它："
        "`--ds-contrast-ok:\"白字压在同级 .ov 的 rgba(0,0,0,.85) 蒙版上，非本元素背景\"`。"
        "写成 CSS 自定义属性而不是注释，因为构建流程会剥掉注释。滥用等于关掉无障碍检查，务必写清理由。",
        "",
        MD_END,
    ]
    return "\n".join(out)


def render_wash_table(t: dict) -> str:
    """同色系色块（chip/tag/badge）的不透明度上限——直接从 tokens 算，不手写。"""
    card = t["color"]["card-bg"]["value"]
    body = t["meta"]["contrast_target_body"]
    # (wash token, 同色系基色, 首选 ink, 兜底 deep)
    pairs = [
        ("brand-wash", "brand", "brand-deep", None),
        ("accent-wash", "accent", "accent-ink", "accent-deep"),
        ("pop-wash", "pop", "pop-ink", "pop-deep"),
        ("green-wash", "panel-green", "panel-green", None),
    ]
    rows = [
        "### 同色系色块（chip / tag / badge）的不透明度上限",
        "",
        f"色块本身是半透明的，文字真正压在**合成后**的颜色上，不是压在 `{card}` 上。",
        f"下表是每个 wash 在 `--card-bg` 上的合成色，以及配套文字色能否达到 {body}:1。",
        "",
        "| 色块 | 当前不透明度 | 合成后底色 | 配套文字 | 对比度 | 判定 |",
        "|---|---|---|---|---|---|",
    ]
    notes: list[str] = []
    for wash, base, ink, deep in pairs:
        if wash not in t["alpha"]:
            continue
        wash_val = t["alpha"][wash]
        wash_val = wash_val if isinstance(wash_val, str) else wash_val["value"]
        _, alpha = parse_rgba(wash_val)
        blended = composite(wash_val, card)
        ink_hex = t["color"][ink]["value"]
        r_ink = contrast(ink_hex, blended)
        if r_ink >= body:
            rows.append(
                f"| `--{wash}` | {alpha:.2f} | `{blended}` | `--{ink}` | {r_ink:.2f} | 通过 |"
            )
            continue
        ceiling = max_alpha_for(t["color"][base]["value"], ink_hex, card, body)
        if deep:
            deep_hex = t["color"][deep]["value"]
            r_deep = contrast(deep_hex, blended)
            rows.append(
                f"| `--{wash}` | {alpha:.2f} | `{blended}` | `--{deep}` | {r_deep:.2f} | 通过（必须用 `-deep`） |"
            )
            notes.append(
                f"- `--{wash}` 上的 `--{ink}` 只有 {r_ink:.2f}:1，**不达标**。"
                f"`--{ink}` 想达标，同色系色块的不透明度必须 ≤ {ceiling:.2f}，"
                f"而当前是 {alpha:.2f}。所以这个色块上的文字一律用 `--{deep}`（{r_deep:.2f}:1）。"
            )
        else:
            rows.append(
                f"| `--{wash}` | {alpha:.2f} | `{blended}` | `--{ink}` | {r_ink:.2f} | 不达标 |"
            )
            notes.append(
                f"- `--{wash}` 上的 `--{ink}` 只有 {r_ink:.2f}:1，需把不透明度降到 ≤ {ceiling:.2f}。"
            )
    if notes:
        rows += ["", *notes]
    rows += [
        "",
        "**为什么会有 `-deep` 这一档**：`--accent-ink` / `--pop-ink` 是给**纯暖底**设计的，"
        "刚好过线（4.8 左右）。一旦底色被同色系 wash 染过，余量就没了。"
        "`--accent-deep` / `--pop-deep` 专门补这个缺口，命名与既有的 `--brand-deep` 一致。",
    ]
    return "\n".join(rows)


def render_code_table(t: dict) -> str:
    """代码/终端面板是配色禁忌的唯一具名例外，把它的合法范围写死在文档里。"""
    if "code_color" not in t:
        return ""
    cc = t["code_color"]
    dark = cc["dark"]
    body = t["meta"]["contrast_target_body"]

    def val(x):
        return x if isinstance(x, str) else x["value"]

    bg = val(dark["code-bg"])
    tb = val(dark["code-tb"])
    rows = [
        "### 代码 / 终端面板：配色禁忌的唯一具名例外",
        "",
        f"禁忌清单禁止「冷灰蓝调」，但代码高亮是**功能性语义色**，不是装饰。"
        f"这里显式豁免一套 Tokyo Night 风格暗色语法色，且只允许用在代码/终端面板内部。"
        f"面板底色固定 `{bg}`（代码区）/ `{tb}`（标题栏）。",
        "",
        f"| Token | 色值 | 在 `{bg}` 上 | 在 `{tb}` 上 |",
        "|---|---|---|---|",
    ]
    for key, spec in dark.items():
        v = val(spec)
        if key in ("code-bg", "code-tb"):
            rows.append(f"| `--{key}` | `{v}` | 面板底色 | 面板底色 |")
            continue
        rows.append(f"| `--{key}` | `{v}` | {contrast(v, bg):.2f} | {contrast(v, tb):.2f} |")
    light = {k: v for k, v in cc.get("light", {}).items() if not k.startswith("_")}
    if light:
        rows += [
            "",
            "**白底代码面板**（`.code-cl` 这类「极简白底」变体）不能套用上面的暗色语法色——"
            "`#7AA2F7` 在白底只有 2.52:1。白底一律用下面这套，全部由既有品牌 token 派生，不引入新色：",
            "",
            "| Token | 指向 | 语义 |",
            "|---|---|---|",
        ]
        sem = {
            "code-lt-fg": "默认文字",
            "code-lt-kw": "关键字",
            "code-lt-fn": "函数名 / 目录",
            "code-lt-str": "字符串",
            "code-lt-num": "数字 / 常量",
            "code-lt-cmt": "注释",
        }
        card = t["color"]["card-bg"]["value"]
        for key, spec in light.items():
            ref = val(spec)
            target = re.match(r"var\(--([\w-]+)\)", str(ref))
            note = ""
            if target and target.group(1) in t["color"]:
                hexv = t["color"][target.group(1)]["value"]
                note = f" · 在 `{card}` 上 {contrast(hexv, card):.2f}"
            rows.append(f"| `--{key}` | `{ref}`{note} | {sem.get(key, '')} |")
        rows.append("")
        rows.append(f"以上每一项在 `{card}` 上都 ≥{body}:1。")
    return "\n".join(rows)


def inject_matrix(text: str, block: str) -> tuple[str, bool]:
    if MD_START in text and MD_END in text:
        pre, rest = text.split(MD_START, 1)
        _, post = rest.split(MD_END, 1)
        new = pre + block + post
        return new, new != text
    return text, False


# ---------- 主流程 ----------
def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="只校验，不写入")
    args = ap.parse_args()

    t = load_tokens()
    css_block = render_css_block(t)
    sub_hex, sub_rgba = build_migrators(t)

    changed: list[str] = []
    missing: list[str] = []

    for rel in CSS_TARGETS + migrate_targets():
        path = ROOT / rel
        if not path.exists():
            missing.append(rel)
            continue
        original = path.read_text(encoding="utf-8")
        text = original
        if rel in CSS_TARGETS:
            text, _ = inject_css(text, css_block)
        text, _ = migrate_outside_tokens(text, sub_hex, sub_rgba)
        if text != original:
            changed.append(rel)
            if not args.check:
                path.write_text(text, encoding="utf-8")

    dna = ROOT / "brand-dna.md"
    if dna.exists():
        original = dna.read_text(encoding="utf-8")
        # 先迁移旧色值，再注入矩阵：反过来会让迁移表改写刚生成的矩阵内容。
        text, _ = migrate_outside_tokens(original, sub_hex, sub_rgba)
        text, _ = inject_matrix(text, render_matrix(t))
        if text != original:
            changed.append("brand-dna.md")
            if not args.check:
                dna.write_text(text, encoding="utf-8")

    mode = "需要更新" if args.check else "已更新"
    print(f"tokens v{t['meta']['version']} · {len(t['color'])} 个色 token · {mode} {len(changed)} 个文件")
    for c in changed:
        print(f"  - {c}")
    if missing:
        print(f"  (跳过不存在的文件: {', '.join(missing)})")

    if args.check and changed:
        print("\n[FAIL] 上述文件与 tokens.json 不同步，请本地运行 python scripts/build_tokens.py 后提交。")
        return 1
    if args.check:
        print("[OK] 全部文件与 tokens.json 同步。")
    return 0


if __name__ == "__main__":
    sys.exit(main())
